In [3]:
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt
import ta
import numpy as np
pd.options.mode.chained_assignment = None

In [4]:
tickers = pd.read_html("https://en.wikipedia.org/wiki/NIFTY_50", match="Company Name")[0]

In [5]:
tickers['Symbol'] = tickers['Symbol'].astype(str) + '.NS'
tickers

                       Company Name         Symbol                      Sector
0                       Adani Ports  ADANIPORTS.NS              Infrastructure
1                  Apollo Hospitals  APOLLOHOSP.NS                  Healthcare
2                      Asian Paints  ASIANPAINT.NS              Consumer Goods
3                         Axis Bank    AXISBANK.NS                     Banking
4                        Bajaj Auto  BAJAJ-AUTO.NS                  Automobile
5                     Bajaj Finance  BAJFINANCE.NS          Financial Services
6                     Bajaj Finserv  BAJAJFINSV.NS          Financial Services
7                     Bharti Airtel  BHARTIARTL.NS           Telecommunication
8                  Bharat Petroleum        BPCL.NS          Energy - Oil & Gas
9              Britannia Industries   BRITANNIA.NS              Consumer Goods
10                            Cipla       CIPLA.NS             Pharmaceuticals
11                       Coal India   COALINDIA.NS                      Metals
12              Divi's Laboratories    DIVISLAB.NS             Pharmaceuticals
13         Dr. Reddy's Laboratories     DRREDDY.NS             Pharmaceuticals
14                    Eicher Motors   EICHERMOT.NS                  Automobile
15                Grasim Industries      GRASIM.NS                      Cement
16                 HCL Technologies     HCLTECH.NS      Information Technology
17                             HDFC        HDFC.NS          Financial Services
18                        HDFC Bank    HDFCBANK.NS                     Banking
19                        HDFC Life    HDFCLIFE.NS          Financial Services
20                    Hero MotoCorp  HEROMOTOCO.NS                  Automobile
21              Hindalco Industries    HINDALCO.NS                      Metals
22               Hindustan Unilever  HINDUNILVR.NS              Consumer Goods
23                       ICICI Bank   ICICIBANK.NS                     Banking
24                    IndusInd Bank  INDUSINDBK.NS                     Banking
25                          Infosys        INFY.NS      Information Technology
26                      ITC Limited         ITC.NS              Consumer Goods
27                        JSW Steel    JSWSTEEL.NS                      Metals
28              Kotak Mahindra Bank   KOTAKBANK.NS                     Banking
29                  Larsen & Toubro          LT.NS                Construction
30              Mahindra & Mahindra         M&M.NS                  Automobile
31                    Maruti Suzuki      MARUTI.NS                  Automobile
32                     Nestl√© India   NESTLEIND.NS              Consumer Goods
33                             NTPC        NTPC.NS              Energy - Power
34  Oil and Natural Gas Corporation        ONGC.NS          Energy - Oil & Gas
35  Power Grid Corporation of India   POWERGRID.NS              Energy - Power
36              Reliance Industries    RELIANCE.NS          Energy - Oil & Gas
37              State Bank of India        SBIN.NS                     Banking
38       SBI Life Insurance Company     SBILIFE.NS          Financial Services
39                    Shree Cements    SHREECEM.NS                      Cement
40               Sun Pharmaceutical   SUNPHARMA.NS             Pharmaceuticals
41                      Tata Motors  TATAMOTORS.NS                  Automobile
42                       Tata Steel   TATASTEEL.NS                      Metals
43        Tata Consultancy Services         TCS.NS      Information Technology
44           Tata Consumer Products  TATACONSUM.NS              Consumer Goods
45                    Tech Mahindra       TECHM.NS      Information Technology
46                    Titan Company       TITAN.NS           Consumer Durables
47                 UltraTech Cement  ULTRACEMCO.NS                      Cement
48        United Phosphorus Limited         UPL.NS                   Chemicals
49                            Wipro       WIPRO.NS  Information Technology[15]

In [6]:
symbols = tickers.Symbol.to_list()

In [7]:
symbols

['ADANIPORTS.NS',
 'APOLLOHOSP.NS',
 'ASIANPAINT.NS',
 'AXISBANK.NS',
 'BAJAJ-AUTO.NS',
 'BAJFINANCE.NS',
 'BAJAJFINSV.NS',
 'BHARTIARTL.NS',
 'BPCL.NS',
 'BRITANNIA.NS',
 'CIPLA.NS',
 'COALINDIA.NS',
 'DIVISLAB.NS',
 'DRREDDY.NS',
 'EICHERMOT.NS',
 'GRASIM.NS',
 'HCLTECH.NS',
 'HDFC.NS',
 'HDFCBANK.NS',
 'HDFCLIFE.NS',
 'HEROMOTOCO.NS',
 'HINDALCO.NS',
 'HINDUNILVR.NS',
 'ICICIBANK.NS',
 'INDUSINDBK.NS',
 'INFY.NS',
 'ITC.NS',
 'JSWSTEEL.NS',
 'KOTAKBANK.NS',
 'LT.NS',
 'M&M.NS',
 'MARUTI.NS',
 'NESTLEIND.NS',
 'NTPC.NS',
 'ONGC.NS',
 'POWERGRID.NS',
 'RELIANCE.NS',
 'SBIN.NS',
 'SBILIFE.NS',
 'SHREECEM.NS',
 'SUNPHARMA.NS',
 'TATAMOTORS.NS',
 'TATASTEEL.NS',
 'TCS.NS',
 'TATACONSUM.NS',
 'TECHM.NS',
 'TITAN.NS',
 'ULTRACEMCO.NS',
 'UPL.NS',
 'WIPRO.NS']

In [39]:
df = yf.download(symbols[36], start='2010-01-01')

[*********************100%***********************]  1 of 1 completed

In [40]:
df

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2010-01-04,540.427307,540.427307,506.127411,532.700500,484.266113,35372156
2010-01-05,569.551208,569.551208,527.697937,530.323059,482.104797,9872785
2010-01-06,534.879883,542.111328,530.298279,538.891846,489.894440,10933743
2010-01-07,538.891846,552.265076,533.938782,547.832092,498.021820,12090336
2010-01-08,548.797974,551.670715,542.854309,546.395691,496.716064,6973331
...,...,...,...,...,...,...
2022-06-02,2634.000000,2732.449951,2634.000000,2724.300049,2724.300049,10211408
2022-06-03,2744.000000,2817.350098,2742.000000,2779.500000,2779.500000,11048210
2022-06-06,2780.000000,2814.000000,2751.800049,2767.550049,2767.550049,5119488
2022-06-07,2769.899902,2791.100098,2752.050049,2772.750000,2772.750000,5703333
2022-06-08,2772.750000,2781.000000,2716.300049,2724.050049,2724.050049,5758596

In [41]:
def tacalc(df):
    df['sma200'] = ta.trend.sma_indicator(df.Close, window=200)
    df['rsi'] = ta.momentum.rsi(df.Close, window=10)
    df['signal'] = np.where((df.Close > df.sma200) & (df.rsi<30), True, False)

In [42]:
def getactuals(df):
    buying_dates = []
    selling_dates = []

    for i in range(len(df)-11):
        if df.signal.iloc[i]:
            buying_dates.append(df.iloc[i+1].name)
            for j in range(1,11):
                if df['rsi'].iloc[i+j] > 40:
                    selling_dates.append(df.iloc[i+j+1].name)
                    break
                elif j==10:
                    selling_dates.append(df.iloc[i+j+1].name)
                    
    frame = pd.DataFrame({'buying_dates':buying_dates, 'selling_dates':selling_dates})
    actuals = frame[frame.buying_dates > frame.selling_dates.shift(1)]
    actuals = frame[:1].append(actuals)
                    
    return actuals

In [43]:
tacalc(df)
actuals = getactuals(df)

In [44]:
profits = \
(df.loc[actuals.selling_dates].Open.values - df.loc[actuals.buying_dates].Open.values)/df.loc[actuals.buying_dates].Open.values

In [45]:
profits

array([ 0.00019084,  0.02843363,  0.02002891,  0.02006336,  0.01016343,
        0.00528297,  0.02122538,  0.02764901,  0.05092458,  0.05312251,
        0.00075709, -0.05508072,  0.05775701,  0.01818182,  0.02709644])

In [46]:
sum(profits)

0.2857962463502204

# Test on all companies

In [1]:
matrixprofits = []

for i in range(len(symbols)):
    df = yf.download(symbols[i], start='2010-01-01')
    tacalc(df)
    actualtrades = getactuals(df)
    profits = \
    (df.loc[actualtrades.selling_dates].Open.values - df.loc[actualtrades.buying_dates].Open.values)/df.loc[actualtrades.buying_dates].Open.values
    matrixprofits.append(profits)

NameError: name 'symbols' is not defined

In [48]:
matrixprofits

[array([ 0.03544132,  0.03996283,  0.0781934 ,  0.03566082,  0.01648805,
        -0.00735291,  0.08345534, -0.01976285]),
 array([ 0.03322156,  0.06      ,  0.05348846,  0.06704824,  0.03759927,
        -0.08774725,  0.02192496,  0.04601469,  0.0114735 ]),
 array([ 0.01454819, -0.05200383,  0.01970359,  0.01473509,  0.03332173,
         0.01381691,  0.00242827,  0.04250988,  0.02424489,  0.02418705,
         0.00645161,  0.00245399, -0.11745215,  0.0151762 ,  0.01298701,
         0.01175348,  0.03325416,  0.03565167, -0.07086523,  0.04504132,
         0.0373913 ,  0.04302521,  0.0283871 ]),
 array([ 0.02928576,  0.00602141, -0.00036276,  0.02538071, -0.05785058,
         0.024     ,  0.04823927, -0.0399274 ,  0.03295876,  0.03373416,
        -0.01227981, -0.02779794,  0.05199819,  0.03126525]),
 array([ 0.01084746, -0.04417292,  0.01803069, -0.04101492,  0.00068701,
         0.01224078,  0.01452785,  0.01237998,  0.01467505, -0.00455927,
         0.04020062,  0.01172638, -0.13770053,  0.04904311, -0.00630247,
        -0.04181185,  0.02113802]),
 array([ 0.01783273,  0.04296301,  0.01215201,  0.03656594,  0.02625497,
         0.0402987 ,  0.02963888,  0.02279663,  0.08853965,  0.03879298,
         0.05702138, -0.15323368,  0.05347901,  0.02031686, -0.21264822,
         0.02308609, -0.20681818,  0.04258041,  0.0189632 ,  0.02285714,
         0.05115942]),
 array([-0.01219385, -0.0071136 ,  0.00951746,  0.03082153,  0.03061223,
         0.02343749,  0.03335512,  0.01165787,  0.02793253,  0.05064028,
         0.01733102,  0.02710147,  0.0778865 ,  0.05276417,  0.04862745,
         0.00302607,  0.00468471, -0.09983498,  0.03847167, -0.02997988,
        -0.20555556,  0.06404762,  0.03490515,  0.00309598,  0.07430629]),
 array([ 0.04276929,  0.05538465,  0.01780107, -0.06008179, -0.14197531,
         0.00025135, -0.00271141, -0.08522119, -0.08241515,  0.0008482 ,
        -0.02164665,  0.04528556]),
 array([ 0.04378205,  0.00558138,  0.02930869,  0.00664736, -0.02745098,
        -0.03573835,  0.03582085,  0.0418549 ,  0.05967932,  0.02539834,
        -0.05464479,  0.04502119, -0.03890022,  0.0531111 ,  0.02252995,
         0.        ,  0.00894531, -0.00272112]),
 array([-0.00863132,  0.01348315,  0.04622873,  0.02486236,  0.01575305,
        -0.00896224,  0.03720137, -0.02105956,  0.03024998,  0.02504638,
        -0.07622086, -0.05846018, -0.01106392,  0.04756597,  0.01230338,
         0.0168978 ,  0.03637791, -0.02763158]),
 array([ 0.04325513, -0.02027652,  0.04343373,  0.03664921,  0.02992363,
         0.01856235, -0.02608696,  0.02931034,  0.03298611,  0.04491932,
         0.03568574,  0.00726998,  0.01208611]),
 array([ 0.05379003,  0.05634837, -0.10663621,  0.02890726,  0.01377462,
        -0.03171094,  0.03909089,  0.00310559,  0.09617651]),
 array([-0.06137256,  0.0419617 ,  0.01152655,  0.01993575,  0.00302826,
         0.02884615,  0.03208909, -0.01363636,  0.00752298, -0.00470343,
        -0.0049505 ,  0.03361998,  0.01134848,  0.02774997,  0.01699909,
         0.03757225, -0.0076925 ,  0.04462103,  0.09636667,  0.02485138]),
 array([-0.02222222,  0.03225806,  0.01179554, -0.00944238, -0.04879555,
        -0.02107598,  0.01727982,  0.03733022,  0.00757576, -0.07117296,
         0.04159948,  0.03039216,  0.01500801,  0.04553267,  0.03307635,
         0.03512327,  0.01931611,  0.01876563,  0.03065539,  0.00412797]),
 array([-0.00920501,  0.08077999,  0.02867548,  0.09421978,  0.01623377,
         0.01712055, -0.01704922, -0.0064255 ,  0.00077789, -0.04675488,
        -0.04050044,  0.02080537, -0.07284472,  0.01800869, -0.05818767,
         0.01781711,  0.04653609,  0.02512479, -0.00945749,  0.02277886,
         0.02698724, -0.01519273,  0.01155041]),
 array([ 0.01443186,  0.04650115,  0.02331609,  0.02168559,  0.01196471,
         0.01634307, -0.00986841,  0.03215783,  0.012363  ,  0.054666  ,
         0.00027476,  0.03969461,  0.02308666,  0.01921275,  0.05153701,
         0.01454294]),
 array([-0.0313813 ,  0.0411765 ,  0.00881743, -0.17118264,  0.05621847,
         0.02022472,  0.0379085 ,  0.04352742,  0.01999625,  0.01265824,
         0.01926606,  0.01060771,  0.01794872,  0.01142658, -0.0113583 ]),
 array([ 0.04174557,  0.01169474, -0.00515963,  0.01963412, -0.02066733,
         0.01349938, -0.01303659,  0.04408504,  0.02218883,  0.01125925,
         0.01071384,  0.03528864,  0.09252094,  0.01639344]),
 array([ 0.04808334,  0.03236246,  0.03390931,  0.00766127,  0.03072002,
        -0.00475835,  0.0245825 ,  0.00502993,  0.01864668,  0.01477034,
         0.01439835, -0.00372887,  0.00724956, -0.01061492, -0.05556766,
         0.01653257,  0.04894002, -0.00016382]),
 array([0.04489437, 0.02862688, 0.01672535]),
 array([-0.01002477,  0.00678143,  0.04123711, -0.030837  ,  0.03206473,
         0.00620176,  0.00512821, -0.05996759]),
 array([ 0.04243178, -0.00177309,  0.02390179,  0.06353961,  0.00145533,
        -0.01504514,  0.0333333 , -0.13458668]),
 array([-0.03368794,  0.00141781,  0.00369286, -0.048     ,  0.03128518,
         0.01344229,  0.02995514, -0.00075061,  0.02367189,  0.01078679,
         0.02928951,  0.02499489,  0.01578688, -0.01020408,  0.02531929,
         0.01624309, -0.05254963]),
 array([ 0.06527902,  0.05118118,  0.05796861,  0.02943227,  0.03947756,
         0.01940403,  0.05038168,  0.07607797, -0.03614245, -0.01428808,
         0.08674734,  0.02270711,  0.05674192,  0.0181997 , -0.37831582,
         0.0291022 ]),
 array([ 0.04040814,  0.04706388,  0.01210004,  0.01674349,  0.03940827,
         0.06145251,  0.02471831, -0.06114286,  0.02912071, -0.03281518,
         0.02209519, -0.00705502,  0.22600779,  0.04705882, -0.00195021]),
 array([ 0.01000033, -0.01637723,  0.01172614, -0.00317499,  0.02882386,
         0.02967322,  0.03614041, -0.09399126]),
 array([-0.03055303,  0.00433231,  0.04956526,  0.02006084,  0.00343645,
         0.02969982,  0.04750076, -0.00704673,  0.02152204,  0.00593774,
         0.00694927,  0.02864966,  0.00744602]),
 array([ 0.03736005, -0.0274089 , -0.06746794,  0.05491291, -0.06620485,
         0.01408852,  0.06217071,  0.02642276,  0.03367003,  0.04112424,
         0.03772503,  0.06087641]),
 array([0.05606427, 0.00316313, 0.04855767, 0.03797288, 0.04243395,
        0.02853329, 0.00334672, 0.00778486, 0.01377796, 0.02562969,
        0.01779755, 0.00061623]),
 array([ 0.04679656, -0.11122989,  0.02765278,  0.02024737, -0.04275165,
         0.03377028, -0.0424411 ,  0.05053534, -0.00129862,  0.03142864,
         0.02513966, -0.03450727,  0.01312496, -0.00838048, -0.02686567,
        -0.04576976,  0.04599557,  0.04912877,  0.01984127,  0.01010101]),
 array([ 0.00311023, -0.00941632,  0.02391304,  0.01277039,  0.01200102,
         0.03617322, -0.1167588 ,  0.0105645 ,  0.02295918,  0.06763926,
         0.02559812]),
 array([ 0.02138527, -0.08979759,  0.01760027, -0.00523582,  0.0096123 ,
         0.03297443,  0.02460996,  0.04668233,  0.02066711,  0.00959233,
        -0.08010402, -0.11924439,  0.00667203,  0.06415929,  0.01108614,
         0.05709406,  0.01781203,  0.01176156]),
 array([-0.06205319,  0.01038238,  0.01401246, -0.02694669,  0.04823143,
         0.03227958, -0.04440154,  0.03238618,  0.03713517, -0.01808429,
        -0.05062788,  0.00763126, -0.08073394,  0.0374504 , -0.05033914,
         0.02447586, -0.00677701,  0.00815112,  0.02335345,  0.02769824,
        -0.01759644]),
 array([ 0.00602405,  0.01858224, -0.00870098,  0.01069357,  0.02452323,
         0.01718626,  0.01011736,  0.0495119 ]),
 array([0.02293578, 0.02376891, 0.08178143, 0.03548332, 0.0267559 ,
        0.01541377, 0.03867403, 0.0156873 , 0.06323301, 0.02854555,
        0.04813032, 0.03825484]),
 array([0.00816126, 0.03475584, 0.02915566, 0.00562982, 0.02936512,
        0.01449274, 0.0254479 ]),
 array([ 0.00019084,  0.02843363,  0.02002891,  0.02006336,  0.01016343,
         0.00528297,  0.02122538,  0.02764901,  0.05092458,  0.05312251,
         0.00075709, -0.05508072,  0.05775701,  0.01818182,  0.02709644]),
 array([ 0.0593056 ,  0.02459019, -0.02168675, -0.03489238,  0.04876034,
         0.02234352,  0.06735397,  0.0322976 ,  0.03161767,  0.06418919,
         0.03202847, -0.11427251,  0.03614458,  0.01388889,  0.01214313,
        -0.02833335]),
 array([0.04385965, 0.03559474, 0.        ]),
 array([-5.76700318e-02,  4.00154844e-02,  7.36961451e-02,  4.19105013e-02,
         5.55379088e-02, -2.16348186e-02,  3.47712797e-02,  4.27132701e-02,
         6.06136821e-03, -3.23949763e-02, -2.28650138e-01,  2.80758159e-02,
        -3.55805243e-03, -1.75473099e-04]),
 array([-0.0484631 , -0.03922762,  0.03855452,  0.04097884,  0.06860707,
         0.01843904,  0.05153563,  0.02353472,  0.05687102,  0.02509963,
         0.03406025]),
 array([ 0.02518891,  0.05789569,  0.04579298,  0.02564101,  0.00409494,
        -0.05783931,  0.02664099,  0.03802753, -0.01803824,  0.09276492,
        -0.03531716,  0.04165173,  0.0528644 ,  0.00033718,  0.07529558]),
 array([ 0.04173623, -0.025485  ,  0.02231636,  0.03286003, -0.02758988,
         0.02971206, -0.00223212,  0.11700468,  0.0819378 , -0.00788773,
         0.06298557,  0.03167725, -0.08875448]),
 array([ 0.04047826,  0.00556861,  0.00108817,  0.02768313,  0.04268891,
         0.0127711 ,  0.0104    ,  0.02230474, -0.03762887, -0.00093985,
         0.02450645,  0.02188552, -0.00337079,  0.03770869]),
 array([-0.02624893,  0.05776696, -0.02290325,  0.        , -0.08320612,
         0.02614151, -0.00792416,  0.01804978, -0.01657249, -0.13117786,
         0.04919373,  0.03898841,  0.004245  ,  0.03294749,  0.00815129]),
 array([ 0.0508769 , -0.04856499,  0.02104375,  0.02971311,  0.03257241,
         0.04117647,  0.02385621, -0.00612706,  0.0234375 ,  0.04041916,
         0.00513161, -0.19137466, -0.08910579]),
 array([ 0.07636229,  0.06084412,  0.04      ,  0.02490711,  0.05057517,
         0.02106601,  0.01234568,  0.01932201,  0.0690636 , -0.00181324,
        -0.01119724,  0.03180212,  0.03058321,  0.01159293,  0.05328749]),
 array([ 0.04289941, -0.01317025,  0.01909814,  0.01746956,  0.0604794 ,
         0.03215562,  0.06413508,  0.05267825,  0.03848237,  0.028623  ,
         0.02934562,  0.0322818 ,  0.03676167,  0.00974189,  0.01586954,
         0.0113291 ]),
 array([ 0.04603849,  0.03689838,  0.0290863 ,  0.06490876,  0.02368425,
         0.07371425,  0.04001329,  0.0533129 ,  0.01871367, -0.00707036,
        -0.13463982, -0.02064024, -0.06141816,  0.03174607,  0.02805755]),
 array([ 0.01904201,  0.02270096, -0.14907621, -0.07122774,  0.00801396,
         0.01616918,  0.02541479, -0.01777333,  0.01171871,  0.00504204,
         0.04225122, -0.12360416])]

In [49]:
s = 0
for element in matrixprofits:
    s += sum(element)

# Check today

In [53]:
def buysell(df):
    df['sma200'] = ta.trend.sma_indicator(df.Close, window=200)
    df['rsi'] = ta.momentum.rsi(df.Close, window=10)
    df['buy'] = np.where((df.Close > df.sma200) & (df.rsi<30), 'Yes', 'No')
    df['sell'] = np.where((df.Close < df.sma200) | (df.rsi>40), 'Yes', 'No')
    
    print(df)

                  Open        High         Low       Close   Adj Close  \
Date
2010-01-04  154.125000  156.825012  152.088760  156.105011  137.027161
2010-01-05  156.667511  159.300003  156.048752  158.568756  139.189835
2010-01-06  158.850006  159.750000  154.575012  155.362503  136.375397
2010-01-07  156.375000  156.487503  151.875000  152.606262  133.956009
2010-01-08  152.775009  153.000000  149.850006  150.311264  131.941498
...                ...         ...         ...         ...         ...
2022-06-02  471.799988  476.450012  468.100006  474.149994  474.149994
2022-06-03  479.649994  488.000000  474.500000  475.500000  475.500000
2022-06-06  472.000000  475.500000  464.200012  473.200012  473.200012
2022-06-07  470.000000  470.750000  465.149994  467.649994  467.649994
2022-06-08  471.049988  472.000000  464.299988  470.399994  470.399994

              Volume      sma200        rsi  signal buy sell
Date
2010-01-04   3409626         NaN        NaN   False  No   No
2010-01-05   4979701         NaN        NaN   False  No   No
2010-01-06   4575030         NaN        NaN   False  No   No
2010-01-07   4582648         NaN        NaN   False  No   No
2010-01-08   2856839         NaN        NaN   False  No   No
...              ...         ...        ...     ...  ..  ...
2022-06-02   5267520  608.629750  48.449785   False  No  Yes
2022-06-03  11634889  607.978000  49.377282   False  No  Yes
2022-06-06   6895578  607.266501  47.750942   False  No  Yes
2022-06-07   2350671  606.534501  43.876227   False  No  Yes
2022-06-08   2812885  605.712000  46.276274   False  No  Yes

[3068 rows x 11 columns]